jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build static files
        id: build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm run generate-pdf

      - name: Upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
